### ISSUE TITLE
Features I want 'uwu'

### ISSUE THREAD

**Issue by CroaBeast** [BryanGamingDV/ChatLab#14]
**Is your feature request related to a problem? Please describe.**
1. LockLogin preLoginEvent compatibility: 
Whether the plugin should use LockLogin's login event to send join messages over the regular Join event. This option will only send join message once a player successfully logs/registers in.
2. CMI Vanish Hook: Send a quit message when a player vanishes, and send a join message when a player unvanishes with the vanish of CMI.
3. First Join/Join messages and commands (maybe?) per world/world groups.

**Describe the solution you'd like**
I explain it above.

**Additional Information**
I'm a furry uwu

**Comment by CroaBeast** [comment]
4. Add an option/module to edit the advancement/achievement messages, and support for custom advancements (datapack or plugin advancements)

**Comment by MartinLite** [comment]
Buenas les vengo a decir un error es que no lo encuentro en aternos y queria ver si me lo pueden solucionar?

**Comment by BryanGamingDV** [comment]
Está en la pagina 9? @MartinLite

**Comment by MartinLite** [comment]
Malardo no lo encuentro

**Comment by MartinLite** [comment]
po de discord?

**Comment by MartinLite** [comment]
tienen grupo*

**Comment by 4drian3d** [comment]
> Buenas les vengo a decir un error es que no lo encuentro en aternos y queria ver si me lo pueden solucionar?

No es problema del plugin, es tema de Aternos agregar el plugin, o que alguien les sugiera añadirlo.

**Comment by BryanGamingDV** [comment]
Si, está en la descripción del github, o puedes entrar aca: https://discord.gg/nnDnMjys

**Comment by BryanGamingDV** [comment]
Y sí está en aternos: https://aternos.org/addons/list/1/chatlab

**Comment by MartinLite** [comment]
fueron troleados por alguien de ds

**Comment by CroaBeast** [comment]
wtf

**Comment by BryanGamingDV** [comment]
Coming soon in 2.2
